// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSs0Si85rFWrsY7zXMPHETxOq-xZ5XRRY',
    appId: '1:934150773887:web:7c9f5829e9c9efc271b34a',
    messagingSenderId: '934150773887',
    projectId: 'moodjurnalapp',
    authDomain: 'moodjurnalapp.firebaseapp.com',
    storageBucket: 'moodjurnalapp.firebasestorage.app',
    measurementId: 'G-T0ESVMGRLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqG7kyarqTQJQGd34Pqo4t3n5jE2CsKnM',
    appId: '1:934150773887:android:d7d14b14a70e847371b34a',
    messagingSenderId: '934150773887',
    projectId: 'moodjurnalapp',
    storageBucket: 'moodjurnalapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP0sWCEj3rtwMdOP1aiOMVnv-BMcHTuxI',
    appId: '1:934150773887:ios:ba385cd41dc0823971b34a',
    messagingSenderId: '934150773887',
    projectId: 'moodjurnalapp',
    storageBucket: 'moodjurnalapp.firebasestorage.app',
    iosBundleId: 'com.example.moodJurnal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP0sWCEj3rtwMdOP1aiOMVnv-BMcHTuxI',
    appId: '1:934150773887:ios:ba385cd41dc0823971b34a',
    messagingSenderId: '934150773887',
    projectId: 'moodjurnalapp',
    storageBucket: 'moodjurnalapp.firebasestorage.app',
    iosBundleId: 'com.example.moodJurnal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSs0Si85rFWrsY7zXMPHETxOq-xZ5XRRY',
    appId: '1:934150773887:web:6a72aca0f20c591871b34a',
    messagingSenderId: '934150773887',
    projectId: 'moodjurnalapp',
    authDomain: 'moodjurnalapp.firebaseapp.com',
    storageBucket: 'moodjurnalapp.firebasestorage.app',
    measurementId: 'G-8S38FQ6JM2',
  );
}
