// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVIxWlxJr7blq04co3FEvJbqJ1SAl0xdI',
    appId: '1:817463415848:web:c3e5ff9bf418112d8ed11d',
    messagingSenderId: '817463415848',
    projectId: 'moodjurnal-bbf83',
    authDomain: 'moodjurnal-bbf83.firebaseapp.com',
    storageBucket: 'moodjurnal-bbf83.firebasestorage.app',
    measurementId: 'G-RWJX2B80FZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBaCCBRMi10nDOm4MiNeIuCBquiJKXVOQ',
    appId: '1:817463415848:android:c389e9fbf4dcc3388ed11d',
    messagingSenderId: '817463415848',
    projectId: 'moodjurnal-bbf83',
    storageBucket: 'moodjurnal-bbf83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5x0IkHKxsqpDCF4IheeiZtamdya81s9U',
    appId: '1:817463415848:ios:241c3297c9e069068ed11d',
    messagingSenderId: '817463415848',
    projectId: 'moodjurnal-bbf83',
    storageBucket: 'moodjurnal-bbf83.firebasestorage.app',
    iosBundleId: 'com.example.moodJurnal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5x0IkHKxsqpDCF4IheeiZtamdya81s9U',
    appId: '1:817463415848:ios:241c3297c9e069068ed11d',
    messagingSenderId: '817463415848',
    projectId: 'moodjurnal-bbf83',
    storageBucket: 'moodjurnal-bbf83.firebasestorage.app',
    iosBundleId: 'com.example.moodJurnal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVIxWlxJr7blq04co3FEvJbqJ1SAl0xdI',
    appId: '1:817463415848:web:517e6bc523e0d5df8ed11d',
    messagingSenderId: '817463415848',
    projectId: 'moodjurnal-bbf83',
    authDomain: 'moodjurnal-bbf83.firebaseapp.com',
    storageBucket: 'moodjurnal-bbf83.firebasestorage.app',
    measurementId: 'G-5JSCJJ3DEE',
  );
}
